# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.20240517.2-1-g40ca1f0
_src_path: gh:level12/copier-py-package
author_email: randy.syring@level12.io
author_name: Randy Syring
project_name: env-config-cli
py_module: env_config
python_version: '3.12'
script_name: env-config
use_pipx: true
